#define SUBSYSTEM_DRIVEBASE			(1 << 0)
#define SUBSYSTEM_LIFTER			(1 << 1)
#define SUBSYSTEM_GRABBER			(1 << 2)
#define SUBSYSTEM_DIGITALIO			(1 << 4)
#define SUBSYSTEM_PDPCURRENTS		(1 << 3)
#define SUBSYSTEM_TELEOP            (1 << 5)
#define SUBSYSTEM_PANEL             (1 << 6)
#define SUBSYSTEM_GEAR_SHIFTER      (1 << 7)

#define SUBSYSTEM_ALL				(0xffffffffffffffff)
