#
# makefile for the misc library
#

#
# define our target library
#
TARGET=util.a

#
# define the source code files
#
SRC = \
	auto_distances.cpp\
	bound_tracker.cpp\
	countdown_timer.cpp\
	countup_timer.cpp\
	debounce.cpp\
	driver_station_interface.cpp\
	fixVictor.cpp\
	input.cpp\
	interface.cpp\
	meta.cpp\
	motion_profile.cpp\
	negedge_trigger.cpp\
	network.cpp\
	output.cpp\
	perf_tracker.cpp\
	persistent_tracker.cpp\
	point.cpp\
	posedge_toggle.cpp\
	posedge_trigger.cpp\
	posedge_trigger_debounce.cpp\
	settable_constant.cpp\
	settable_toggle.cpp\
	speed_tracker.cpp\
	stall_monitor.cpp\
	string_utils.cpp\
	type.cpp\
	util.cpp\
	visitable.cpp

TESTS = \
	auto_distances.cpp\
	auto_distances.cpp\
	bound_tracker.cpp\
	countdown_timer.cpp\
	countup_timer.cpp\
	debounce.cpp\
	driver_station_interface.cpp\
	fixVictor.cpp\
	input.cpp\
	interface.cpp\
	meta.cpp\
	motion_profile.cpp\
	negedge_trigger.cpp\
	network.cpp\
	network.cpp\
	network.cpp\
	output.cpp\
	perf_tracker.cpp\
	persistent_tracker.cpp\
	point.cpp\
	posedge_trigger.cpp\
	posedge_trigger_debounce.cpp\
	settable_constant.cpp\
	settable_toggle.cpp\
	speed_profile.cpp\
	speed_tracker.cpp\
	stall_monitor.cpp\
	string_utils.cpp\
	type.cpp\
	type.cpp\
	util.cpp\
	visitable.cpp


#
# include a central make file that defines our compilation recipe
#
include ../../../makefiles/compilelib.mk
