#
# makefile for the misc library
#

#
# define our target library
#
TARGET=util.a

#
# define the source code files
#
SRC = \
	paramsParser.cpp


#
# include a central make file that defines our compilation recipe
#
include ../../../makefiles/compilelib.mk
