#
# makefile for the executive library
#

#
# define our target library
#
TARGET=executive.a

#
# define our source code
#
SRC = \
	align.cpp\
	autonomous.cpp\
	chain.cpp\
	executive.cpp\
	step.cpp\
	teleop.cpp\
	test.cpp\
	timed.cpp

#
# include a central make file that defines our compilation recipe
#
include ../../../makefiles/compilelib.mk

