#
# makefile for the control library
#

#
# define our target library
#
TARGET=control.a

#
# define the source code files
#
SRC = \
	drivebase.cpp\
	force.cpp\
	force_interface.cpp\
	lights.cpp\
	log.cpp\
	main.cpp\
	monitor.cpp\
	motor_check.cpp\
	nop.cpp\
	pump.cpp\
	sim.cpp\
	pidctrl.cpp\
	toplevel.cpp

#
# include a central make file that defines our compilation recipe
#
include ../../../makefiles/compilelib.mk

