#
# makefile for the misc library
#

#
# define our target library
#
TARGET=helpers.a

#
# define the source code files
#
SRC = \
	data_logger.cpp\
	destination_server.cpp

# message_logger.cpp

TESTS = \
	destination_server.cpp
#
# include a central make file that defines our compilation recipe
#
include ../../../makefiles/compilelib.mk
