#
# makefile for the misc library
#

#
# define our target library
#
TARGET=helpers.a

#
# define the source code files
#
SRC = \
	params_parser.cpp\
	message_logger.cpp

# message_logger.cpp

TESTS = \
	params_parser.cpp\
	message_logger.cpp
#
# include a central make file that defines our compilation recipe
#
include ../../../makefiles/compilelib.mk
